{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"scouting area\",\"scouting career_entry\",\"scouting competition\",\"scouting competition_season\",\"scouting match\",\"scouting match_event_carry\",\"scouting match_event_infraction\",\"scouting match_event_other\",\"scouting match_event_pass\",\"scouting match_event_shot\",\"scouting match_formation\",\"scouting match_lineup\",\"scouting match_lineup_player_position\",\"scouting match_substitution\",\"scouting player\",\"scouting player_match_stats\",\"scouting player_positions\",\"scouting round\",\"scouting team\",\"scouting team_competition_season\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.122.746.0 (23.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-PT",
    "cultures": [
      {
        "name": "pt-PT",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "bbcdad09-09d5-460d-9a97-5a05a336cfc5",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "player",
        "fromTable": "scouting career_entry",
        "toColumn": "idplayer",
        "toTable": "scouting player"
      },
      {
        "name": "bfba9c42-4d68-42c6-b458-cef54ad8161b",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "area",
        "fromTable": "scouting competition",
        "toColumn": "idareas",
        "toTable": "scouting area"
      },
      {
        "name": "48035cf2-fc76-47ee-ab8b-0452bab84ef5",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "competition",
        "fromTable": "scouting competition_season",
        "toColumn": "idcompetitions",
        "toTable": "scouting competition"
      },
      {
        "name": "522a6ac3-f590-4c9f-b541-ae72e51cccf0",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "away_team",
        "fromTable": "scouting match",
        "toColumn": "idteam",
        "toTable": "scouting team"
      },
      {
        "name": "364370ea-eee9-4b08-a1f9-720c3c1298dd",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "home_team",
        "fromTable": "scouting match",
        "isActive": false,
        "toColumn": "idteam",
        "toTable": "scouting team"
      },
      {
        "name": "43db8d38-7a9f-401a-95f3-276968d0a99f",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "match",
        "fromTable": "scouting match_event_carry",
        "toColumn": "idmatch",
        "toTable": "scouting match"
      },
      {
        "name": "e3c1072c-d4d7-4e83-84d4-3549b7c240a3",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "match",
        "fromTable": "scouting match_event_infraction",
        "toColumn": "idmatch",
        "toTable": "scouting match"
      },
      {
        "name": "d7dfb33c-8e1a-4fc9-8940-39322238fa44",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "match",
        "fromTable": "scouting match_event_other",
        "toColumn": "idmatch",
        "toTable": "scouting match"
      },
      {
        "name": "0eb82629-830b-432a-a265-f17ad3e16ef9",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "match",
        "fromTable": "scouting match_event_pass",
        "toColumn": "idmatch",
        "toTable": "scouting match"
      },
      {
        "name": "a7ff8fb2-d063-4cde-8500-8136ed2dd060",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "match",
        "fromTable": "scouting match_event_shot",
        "toColumn": "idmatch",
        "toTable": "scouting match"
      },
      {
        "name": "fb7f1a23-ac9e-4fa0-bdd1-930f5d5b949d",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "match",
        "fromTable": "scouting match_formation",
        "toColumn": "idmatch",
        "toTable": "scouting match"
      },
      {
        "name": "ad2aefa7-c82e-43c1-8e5b-ed4780181450",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "player",
        "fromTable": "scouting match_formation",
        "toColumn": "idplayer",
        "toTable": "scouting player"
      },
      {
        "name": "607df6f4-d4ed-4a52-80b7-56f0b0e0f229",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "team",
        "fromTable": "scouting match_formation",
        "isActive": false,
        "toColumn": "idteam",
        "toTable": "scouting team"
      },
      {
        "name": "f041d8fc-762a-439f-a331-b2cd560aa8e7",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "match",
        "fromTable": "scouting match_lineup",
        "toColumn": "idmatch",
        "toTable": "scouting match"
      },
      {
        "name": "e1cdff3d-d30b-4802-a338-9d15df0de74f",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "team",
        "fromTable": "scouting match_lineup",
        "isActive": false,
        "toColumn": "idteam",
        "toTable": "scouting team"
      },
      {
        "name": "368e8417-2a51-41cd-986e-39c1d83893d6",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "player",
        "fromTable": "scouting match_lineup_player_position",
        "toColumn": "idplayer",
        "toTable": "scouting player"
      },
      {
        "name": "3d5f9275-4e4d-4621-b64d-f767577b8866",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "match",
        "fromTable": "scouting match_substitution",
        "toColumn": "idmatch",
        "toTable": "scouting match"
      },
      {
        "name": "4609a4e0-0e3b-45e3-95f2-e991faf4f03d",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "playerIn",
        "fromTable": "scouting match_substitution",
        "toColumn": "idplayer",
        "toTable": "scouting player"
      },
      {
        "name": "7eb87217-0c64-4698-be33-6ca72f79f0ad",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "playerOut",
        "fromTable": "scouting match_substitution",
        "isActive": false,
        "toColumn": "idplayer",
        "toTable": "scouting player"
      },
      {
        "name": "bf1ff9de-9168-4111-967a-99b8deb826e6",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "team",
        "fromTable": "scouting match_substitution",
        "isActive": false,
        "toColumn": "idteam",
        "toTable": "scouting team"
      },
      {
        "name": "8eeea256-e54d-4504-8d16-cad81d654ea0",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "birth_area",
        "fromTable": "scouting player",
        "toColumn": "idareas",
        "toTable": "scouting area"
      },
      {
        "name": "0d6223f4-831e-4b2b-862a-82282ab97907",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "match",
        "fromTable": "scouting player_match_stats",
        "toColumn": "idmatch",
        "toTable": "scouting match"
      },
      {
        "name": "d48af7dd-0928-4f85-a705-244523e9df2e",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "player",
        "fromTable": "scouting player_match_stats",
        "toColumn": "idplayer",
        "toTable": "scouting player"
      },
      {
        "name": "9e39b783-56e5-42ae-9104-8f4eedae3326",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "player",
        "fromTable": "scouting player_positions",
        "toColumn": "idplayer",
        "toTable": "scouting player"
      },
      {
        "name": "5c11c318-1190-49af-8ec2-2cc84abfda0a",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "area",
        "fromTable": "scouting team",
        "isActive": false,
        "toColumn": "idareas",
        "toTable": "scouting area"
      },
      {
        "name": "ac5de7d8-a41e-44df-86d4-3313b8361a72",
        "annotations": [
          {
            "name": "PBI_IsFromSource",
            "value": "FS"
          }
        ],
        "fromColumn": "team",
        "fromTable": "scouting team_competition_season",
        "toColumn": "idteam",
        "toTable": "scouting team"
      }
    ],
    "sourceQueryCulture": "pt-PT",
    "tables": [
      {
        "name": "scouting area",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "idareas",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "4afba29f-880c-48d4-8d59-ad9749e7df54",
            "sourceColumn": "idareas",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "alpha3code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f690dd64-251d-4dbc-89d2-b861dc8e8367",
            "sourceColumn": "alpha3code",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "74ea4c34-635b-4a71-93c3-9ef46a2b0038",
            "sourceColumn": "name",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "Flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "expression": "[URLBandeira]",
            "isDataTypeInferred": true,
            "lineageTag": "2adfafdb-ab84-4894-b439-068ba684072c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "2f1263b3-7a4c-4fe9-a8e5-fde446c1767d",
        "measures": [
          {
            "name": "FlagEquipa",
            "expression": [
              "",
              "VAR Pais = SELECTEDVALUE('scouting team'[area])",
              "VAR NomeDoPais =",
              "    CALCULATE(",
              "        VALUES('scouting area'[name]),",
              "        'scouting area'[idareas] = Pais",
              "    )",
              "RETURN \"https://cdn.countryflags.com/thumbs/\" & LOWER(NomeDoPais) & \"/flag-square-250.png\" "
            ],
            "lineageTag": "2afe7526-2f49-4ae3-902d-4eb253d637f3"
          },
          {
            "name": "FlagJogador",
            "dataCategory": "ImageUrl",
            "expression": [
              "",
              "VAR Pais = SELECTEDVALUE('scouting player'[birth_area])",
              "VAR NomeDoPais =",
              "    CALCULATE(",
              "        VALUES('scouting area'[name]),",
              "        'scouting area'[idareas] = Pais",
              "    )",
              "RETURN \"https://cdn.countryflags.com/thumbs/\" & LOWER(NomeDoPais) & \"/flag-square-250.png\" "
            ],
            "lineageTag": "ebf59c42-b48c-4d91-8b2f-3e30d2db5432"
          },
          {
            "name": "País (Competição)",
            "expression": [
              "",
              "VAR PaisCompeticao = SELECTEDVALUE('scouting competition'[area])",
              "RETURN",
              "    CALCULATE(",
              "        VALUES('scouting area'[name]),",
              "        'scouting area'[idareas] = PaisCompeticao",
              "    ) "
            ],
            "lineageTag": "5b28efdb-57d2-4930-b37e-1785df5285d3"
          },
          {
            "name": "País (Equipa)",
            "expression": [
              "",
              "VAR Pais = SELECTEDVALUE('scouting team'[area])",
              "RETURN",
              "    CALCULATE(",
              "        VALUES('scouting area'[name]),",
              "        'scouting area'[idareas] = Pais",
              "    ) "
            ],
            "lineageTag": "5ff481b3-421f-484a-aae9-b68d44204666"
          },
          {
            "name": "País (Jogador)",
            "expression": [
              "",
              "VAR Pais = SELECTEDVALUE('scouting player'[birth_area])",
              "RETURN",
              "    CALCULATE(",
              "        VALUES('scouting area'[name]),",
              "        'scouting area'[idareas] = Pais",
              "    ) "
            ],
            "lineageTag": "d57c6ddc-d208-4fd8-861b-698a29c9a5b5"
          },
          {
            "name": "URLBandeira",
            "expression": [
              "",
              "VAR NomeDoPais = LOWER(VALUES('scouting area'[name]))",
              "VAR URLBase = \"https://cdn.countryflags.com/thumbs/\"  ",
              "RETURN",
              "    URLBase & NomeDoPais & \"/flag-square-250.png\""
            ],
            "lineageTag": "3c729721-7cad-413e-bc0c-d31635265fa2"
          }
        ],
        "partitions": [
          {
            "name": "scouting area",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"prov-sql-azure.database.windows.net\", \"micro-scout\"),",
                "    scouting_area = Origem{[Schema=\"scouting\",Item=\"area\"]}[Data]",
                "in",
                "    scouting_area"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "scouting career_entry",
        "columns": [
          {
            "name": "player",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "afb0ff5f-b0b0-427f-bd31-f67f7793ac75",
            "sourceColumn": "player",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "team_competition_season",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "e523fdff-c420-4f55-9fe2-17c8683c0667",
            "sourceColumn": "team_competition_season",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "appearances",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "253cb719-d102-4f3d-8b88-bda3250c0875",
            "sourceColumn": "appearances",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "goal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7fc54f91-bb0d-48e4-b692-4f136d2d7339",
            "sourceColumn": "goal",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "minutesPlayed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c05a98b5-265c-4493-8d4e-448160df8739",
            "sourceColumn": "minutesPlayed",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "penalties",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0f2dc69b-df90-43f5-a294-2789ee22ab3b",
            "sourceColumn": "penalties",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "redCards",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3f9f4935-3d88-4207-80a2-d48d1bc3f5a3",
            "sourceColumn": "redCards",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "shirtNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cb432090-0b75-467e-837b-7c99f29a8b1b",
            "sourceColumn": "shirtNumber",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "substituteIn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "544e5914-deb2-4326-9523-0d42ef225cca",
            "sourceColumn": "substituteIn",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "substituteOnBench",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "febde30b-99de-4410-8b58-f8b1d7dd3dc4",
            "sourceColumn": "substituteOnBench",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "substituteOut",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "87054ecf-5943-4771-afd2-8ed23deb17f7",
            "sourceColumn": "substituteOut",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "yellowCard",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "07fb5680-5c68-4509-ba89-d03a903b3872",
            "sourceColumn": "yellowCard",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "d1f9da78-42ed-4a71-b642-0bd73b790140",
        "partitions": [
          {
            "name": "scouting career_entry",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"prov-sql-azure.database.windows.net\", \"micro-scout\"),",
                "    scouting_career_entry = Origem{[Schema=\"scouting\",Item=\"career_entry\"]}[Data]",
                "in",
                "    scouting_career_entry"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "scouting competition",
        "columns": [
          {
            "name": "idcompetitions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "7ea73c3b-c389-4e37-bc98-cb1e720a5430",
            "sourceColumn": "idcompetitions",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a95212df-69ad-4916-b523-9b6278e07741",
            "sourceColumn": "name",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2e88114a-3d39-461e-8333-e1e10b4f96d1",
            "sourceColumn": "area",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3838039e-a441-4999-800d-770192949d33",
            "sourceColumn": "gender",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "54ec7b35-8f52-41a6-89de-4b5f01e46873",
            "sourceColumn": "type",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "format",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec83ddce-8504-4581-ba00-0d41c135e4b5",
            "sourceColumn": "format",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "divisionLevel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6855354c-8bc5-44c7-8c7c-b4fd1d982c08",
            "sourceColumn": "divisionLevel",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0a73e3af-a6f8-40b1-85c8-b79095390dfb",
            "sourceColumn": "category",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1765219e-2d9b-455a-9e5c-3b61ff0970d1",
        "partitions": [
          {
            "name": "scouting competition",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"prov-sql-azure.database.windows.net\", \"micro-scout\"),",
                "    scouting_competition = Origem{[Schema=\"scouting\",Item=\"competition\"]}[Data]",
                "in",
                "    scouting_competition"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "scouting competition_season",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "idcompetition_season",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "59abd19b-a5e5-4ab6-9080-623e79f50d7a",
            "sourceColumn": "idcompetition_season",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "startDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "87f4b1ae-5a8a-459d-9464-dc3beaa4e0f0",
            "sourceColumn": "startDate",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "endDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "15c84f92-4d92-4cc6-b9e0-e1d465aaf37d",
            "sourceColumn": "endDate",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9df4a743-da5c-4c31-9c4c-d33b51d98b1f",
            "sourceColumn": "name",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "competition",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "fcecd5e1-afa9-4a53-8781-33a6a258f28c",
            "sourceColumn": "competition",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "icon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02da2385-3f1e-40e6-ac1a-5b891f391761",
            "sourceColumn": "icon",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "Época",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "'scouting competition_season'[startDate] & \"/\" & 'scouting competition_season'[endDate]",
            "isDataTypeInferred": true,
            "lineageTag": "1dd534a2-f3d9-4d01-a04b-9cd960d0f400",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "96a4b034-ecce-4e1d-af08-e3163b690eea",
        "partitions": [
          {
            "name": "scouting competition_season",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"prov-sql-azure.database.windows.net\", \"micro-scout\"),",
                "    scouting_competition_season = Origem{[Schema=\"scouting\",Item=\"competition_season\"]}[Data],",
                "    #\"Ano Extraído\" = Table.TransformColumns(scouting_competition_season,{{\"startDate\", Date.Year, Int64.Type}, {\"endDate\", Date.Year, Int64.Type}})",
                "in",
                "    #\"Ano Extraído\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "scouting match",
        "columns": [
          {
            "name": "idmatch",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "23a8d41f-92df-4267-b4f7-483613985dc2",
            "sourceColumn": "idmatch",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "competition_season",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0509455f-8abe-4d8e-9998-cb265c9a6fae",
            "sourceColumn": "competition_season",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "home_team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "35e0d1a4-48cd-42ce-8c14-e51172ede9d4",
            "sourceColumn": "home_team",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "away_team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fdb38b76-a71c-4622-a360-7fef674c5b42",
            "sourceColumn": "away_team",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "6fa7a872-6c0b-4dd4-ab22-cb1e52473d0b",
            "sourceColumn": "Data",
            "sourceProviderType": "datetime2",
            "summarizeBy": "none"
          },
          {
            "name": "home_score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e6588256-d262-4e63-8067-fb894a1c5375",
            "sourceColumn": "home_score",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "away_score",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "26d366c2-3f9f-4461-9576-41f9aa815cef",
            "sourceColumn": "away_score",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "winner",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "748168ad-6f90-4705-be99-f7197639c4b3",
            "sourceColumn": "winner",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "Hora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Time"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "dateTime",
            "expression": "HOUR('scouting match'[Data]) & \":\" & MINUTE('scouting match'[Data])",
            "formatString": "hh:nn",
            "lineageTag": "945ea4de-e9ca-43ca-839d-e0801d084ff1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "3b1cbd2d-5a89-4edc-8916-b18810fff6e9",
        "measures": [
          {
            "name": "Flag",
            "expression": [
              "",
              "VAR CompetitionSeasonID = SELECTEDVALUE('scouting match'[competition_season])  ",
              "VAR NamePais = 'scouting match'[Pais]",
              "RETURN",
              "    CALCULATE(",
              "        VALUES('scouting area'[Flag]),  ",
              "        'scouting area'[name] = NamePais",
              "    ) "
            ],
            "lineageTag": "fcba1eee-4fc0-4b5b-b6fb-0a415c990c24"
          },
          {
            "name": "IconVisitado",
            "expression": [
              "",
              "VAR HomeTeam = 'scouting match'[Visitado]",
              "RETURN",
              "    CALCULATE(",
              "        VALUES('scouting team'[icon]),",
              "        'scouting team'[name] = HomeTeam",
              "    ) "
            ],
            "lineageTag": "3263e786-5460-4adb-b8f0-b60a69163600"
          },
          {
            "name": "IconVisitante",
            "expression": [
              "",
              "VAR HomeTeam = 'scouting match'[Visitante]",
              "RETURN",
              "    CALCULATE(",
              "        VALUES('scouting team'[icon]),",
              "        'scouting team'[name] = HomeTeam",
              "    ) "
            ],
            "lineageTag": "6ac63b77-f482-4513-a021-34bcee2a7d29"
          },
          {
            "name": "NomeCompeticao",
            "expression": [
              "",
              "VAR CompetitionSeasonID = SELECTEDVALUE('scouting match'[competition_season])  ",
              "RETURN",
              "    CALCULATE(",
              "        VALUES('scouting competition'[name]), ",
              "        FILTER('scouting competition_season', 'scouting competition_season'[idcompetition_season] = CompetitionSeasonID)",
              "    ) "
            ],
            "lineageTag": "1f3e2512-fcd3-44a6-9bdb-93bdb8c8290a"
          },
          {
            "name": "Pais",
            "expression": [
              "",
              "VAR CompetitionSeasonID = SELECTEDVALUE('scouting match'[competition_season])  ",
              "VAR AreaID = ",
              "    CALCULATE(",
              "        VALUES('scouting competition'[area]), ",
              "        FILTER('scouting competition_season', 'scouting competition_season'[idcompetition_season] = CompetitionSeasonID)",
              "    )",
              "RETURN",
              "    CALCULATE(",
              "        VALUES('scouting area'[name]),  -- Substitua 'area' e 'nome' pelos nomes corretos da tabela e da coluna.",
              "        'scouting area'[idareas] = AreaID",
              "    ) "
            ],
            "lineageTag": "db40489e-e202-4e70-ba08-0da94e369374"
          },
          {
            "name": "Vencedor",
            "expression": [
              "",
              "VAR winner = SELECTEDVALUE('scouting match'[winner])",
              "RETURN",
              "    CALCULATE(",
              "        VALUES('scouting team'[name]),",
              "        'scouting team'[idteam] = winner",
              "    ) "
            ],
            "lineageTag": "0c7dd334-f4e0-434f-8fcd-a4f79903997f"
          },
          {
            "name": "Visitado",
            "expression": [
              "",
              "VAR HomeTeamID = SELECTEDVALUE('scouting match'[home_team])",
              "RETURN",
              "    CALCULATE(",
              "        VALUES('scouting team'[name]),",
              "        'scouting team'[idteam] = HomeTeamID",
              "    ) "
            ],
            "lineageTag": "6c56b8ef-a20a-4bdd-b450-0053429ffc61"
          },
          {
            "name": "Visitante",
            "expression": [
              "",
              "VAR AwayTeamID = SELECTEDVALUE('scouting match'[away_team])",
              "RETURN",
              "    CALCULATE(",
              "        VALUES('scouting team'[name]),",
              "        'scouting team'[idteam] = AwayTeamID",
              "    ) "
            ],
            "lineageTag": "4fc853fe-e68a-4de5-a6ca-6b8db2358baf"
          }
        ],
        "partitions": [
          {
            "name": "scouting match",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"prov-sql-azure.database.windows.net\", \"micro-scout\"),",
                "    scouting_match = Origem{[Schema=\"scouting\",Item=\"match\"]}[Data],",
                "    #\"Colunas com Nome Mudado\" = Table.RenameColumns(scouting_match,{{\"date\", \"Data\"}})",
                "in",
                "    #\"Colunas com Nome Mudado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "scouting match_event_carry",
        "columns": [
          {
            "name": "idmatch_event",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "cc8866aa-3782-4866-8785-2f4c243aae4d",
            "sourceColumn": "idmatch_event",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "match",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "e7e15f7f-2105-4683-9845-8aadd7ad93ef",
            "sourceColumn": "match",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "player",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f11027aa-4505-4c95-89e0-f9bbce5bfa7a",
            "sourceColumn": "player",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "matchPeriod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "955f1720-a88a-459f-85df-d53e3642b8d2",
            "sourceColumn": "matchPeriod",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "location_x",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f0f7aa1d-6841-4346-ad18-02c8d809bd71",
            "sourceColumn": "location_x",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "location_y",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0e56e920-7bb0-4731-a0c2-2c3a4f12dd5b",
            "sourceColumn": "location_y",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "minute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ca0a2a3d-a76a-4d61-bd36-684d7e097f1a",
            "sourceColumn": "minute",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "second",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "61c5ee4f-f4b9-412b-8fa6-2dfdfeeced36",
            "sourceColumn": "second",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "endlocation_x",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a26f7922-d8eb-4250-adc4-020cbb14f760",
            "sourceColumn": "endlocation_x",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "endlocation_y",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9f6b2291-5aec-49cb-a216-9e637043b6a9",
            "sourceColumn": "endlocation_y",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "7495c7d0-b4a4-46b7-af34-dda8b8cf39b6",
        "partitions": [
          {
            "name": "scouting match_event_carry",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"prov-sql-azure.database.windows.net\", \"micro-scout\"),",
                "    scouting_match_event_carry = Origem{[Schema=\"scouting\",Item=\"match_event_carry\"]}[Data]",
                "in",
                "    scouting_match_event_carry"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "scouting match_event_infraction",
        "columns": [
          {
            "name": "idmatch_event",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "c61a665c-f548-44ba-9b3f-78a073fbc77f",
            "sourceColumn": "idmatch_event",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "match",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "7ecf373b-d843-4c0e-8389-f0a92eed0549",
            "sourceColumn": "match",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "player",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "27dc9c5f-9b30-4101-adf5-adc1cff1b28c",
            "sourceColumn": "player",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "matchPeriod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f35e4f8-a75b-499a-aa5b-3331f346fbc5",
            "sourceColumn": "matchPeriod",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "location_x",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cec65d73-5da5-4325-83ab-1c4264ba0c80",
            "sourceColumn": "location_x",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "location_y",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1a7936fb-cbc7-4459-8c4a-b85697f1a574",
            "sourceColumn": "location_y",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "minute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fdca4c60-f67c-43ce-bcb3-75776464651c",
            "sourceColumn": "minute",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "second",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1620dd5a-57a5-4525-920b-a95807268a70",
            "sourceColumn": "second",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "yellowCard",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7fb49a4b-960b-4c07-b79b-54d446f00af0",
            "sourceColumn": "yellowCard",
            "sourceProviderType": "smallint",
            "summarizeBy": "sum"
          },
          {
            "name": "redCard",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a2586366-ab0f-491f-aef3-54ccb8e183d7",
            "sourceColumn": "redCard",
            "sourceProviderType": "smallint",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "14a2a576-dcd9-4c1f-a6e6-627cc12c6914",
        "partitions": [
          {
            "name": "scouting match_event_infraction",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"prov-sql-azure.database.windows.net\", \"micro-scout\"),",
                "    scouting_match_event_infraction = Origem{[Schema=\"scouting\",Item=\"match_event_infraction\"]}[Data]",
                "in",
                "    scouting_match_event_infraction"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "scouting match_event_other",
        "columns": [
          {
            "name": "idmatch_event",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "b0559cd0-a282-4008-b9cd-2bbcee94020b",
            "sourceColumn": "idmatch_event",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "match",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "aafd0150-a5f2-4e40-afd8-d5ff8c1e18f2",
            "sourceColumn": "match",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "player",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b25b03f5-0df8-4529-b243-4ff81b8526b7",
            "sourceColumn": "player",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "matchPeriod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1424ad47-7fc0-44f1-8d69-b50dae8701b2",
            "sourceColumn": "matchPeriod",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "location_x",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b10b5fb5-9085-4a05-8fa6-dc7bfa21a5da",
            "sourceColumn": "location_x",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "location_y",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b487bf14-c66e-433b-a03c-e5d52169d274",
            "sourceColumn": "location_y",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "minute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2f113e69-f5bf-453a-bbb7-474d611aec1e",
            "sourceColumn": "minute",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "second",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b7424248-4775-4dd6-a604-fc5fcd27b2b2",
            "sourceColumn": "second",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "100ee651-c3e9-4b1c-88f6-a29854b7d09a",
        "partitions": [
          {
            "name": "scouting match_event_other",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"prov-sql-azure.database.windows.net\", \"micro-scout\"),",
                "    scouting_match_event_other = Origem{[Schema=\"scouting\",Item=\"match_event_other\"]}[Data]",
                "in",
                "    scouting_match_event_other"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "scouting match_event_pass",
        "columns": [
          {
            "name": "idmatch_event",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "4cbd09d0-ec07-4929-b8f9-95d2a2dfdefb",
            "sourceColumn": "idmatch_event",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "match",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "9449f0da-ecf1-49ce-a2f0-526d4ff4da85",
            "sourceColumn": "match",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "player",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a8afee2f-8b96-43b9-9df8-5a081c1c9ca0",
            "sourceColumn": "player",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "matchPeriod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa9ba3c9-5d86-4e85-a2ce-6dec50493990",
            "sourceColumn": "matchPeriod",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "location_x",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5ee14a75-16db-425e-834e-55dd0657d37b",
            "sourceColumn": "location_x",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "location_y",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6e88d2df-951f-4e9d-9cec-6c149b2eebe4",
            "sourceColumn": "location_y",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "minute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c68b7d71-a76e-4b84-849e-fd7c00873f23",
            "sourceColumn": "minute",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "second",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0b5c99a1-bd7d-4fe6-858e-56e17565a8b3",
            "sourceColumn": "second",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "accurate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ccccc6df-f69a-4d14-90be-2488e807bede",
            "sourceColumn": "accurate",
            "sourceProviderType": "smallint",
            "summarizeBy": "sum"
          },
          {
            "name": "recipient",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e577efd8-14db-47e3-9e24-64ed088656f6",
            "sourceColumn": "recipient",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "endlocation_x",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "883bd129-459c-4cc9-9f16-b611740126c3",
            "sourceColumn": "endlocation_x",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "endlocation_y",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d43c27b4-a9e9-4b70-a132-94783ed58837",
            "sourceColumn": "endlocation_y",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "11249c8d-3df5-43d6-9492-d426b1efe093",
        "partitions": [
          {
            "name": "scouting match_event_pass",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"prov-sql-azure.database.windows.net\", \"micro-scout\"),",
                "    scouting_match_event_pass = Origem{[Schema=\"scouting\",Item=\"match_event_pass\"]}[Data]",
                "in",
                "    scouting_match_event_pass"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "scouting match_event_shot",
        "columns": [
          {
            "name": "idmatch_event",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "a9474721-3344-4a37-b286-2b769c06f1bf",
            "sourceColumn": "idmatch_event",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "match",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "06d8c9b2-fa6a-4fc7-a7d8-be2d339e481b",
            "sourceColumn": "match",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "player",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8e22daf5-3f0a-4dcc-983a-3581e972f050",
            "sourceColumn": "player",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "matchPeriod",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "523c466e-391b-462a-8718-cb9285dd4557",
            "sourceColumn": "matchPeriod",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "location_x",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6bca27fb-d94f-4029-ac84-2a4774146dd5",
            "sourceColumn": "location_x",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "location_y",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ee8370d8-e077-457e-9da5-63c1478d7551",
            "sourceColumn": "location_y",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "minute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f29b522d-9fa4-45b1-a853-ed66c9f030e8",
            "sourceColumn": "minute",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "second",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "10bc5f57-2060-4eb9-88c3-3a54fbf4fca8",
            "sourceColumn": "second",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "isGoal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8fd7a965-43e7-4281-b59b-d2e90ab6b651",
            "sourceColumn": "isGoal",
            "sourceProviderType": "smallint",
            "summarizeBy": "sum"
          },
          {
            "name": "onTarget",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2d7d1cc5-b8ce-457d-884a-f426fa4a3557",
            "sourceColumn": "onTarget",
            "sourceProviderType": "smallint",
            "summarizeBy": "sum"
          },
          {
            "name": "xg",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "98168be8-fd72-4f88-b083-184ac40583db",
            "sourceColumn": "xg",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "postShotXg",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "3304b799-3ee4-4ca1-94cb-5008d0c96e6a",
            "sourceColumn": "postShotXg",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "873d8792-150f-4ed2-a107-644396c8a524",
        "partitions": [
          {
            "name": "scouting match_event_shot",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"prov-sql-azure.database.windows.net\", \"micro-scout\"),",
                "    scouting_match_event_shot = Origem{[Schema=\"scouting\",Item=\"match_event_shot\"]}[Data]",
                "in",
                "    scouting_match_event_shot"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "scouting match_formation",
        "columns": [
          {
            "name": "match",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "2bcfe0d4-25e1-4d5e-b461-d3f1f7a9df9c",
            "sourceColumn": "match",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "player",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "7705ebbb-2337-47a1-8699-ae1b6515a2cf",
            "sourceColumn": "player",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "908a5cf3-a502-4a65-be7d-5749fa657453",
            "sourceColumn": "team",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "assists",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "235059ec-302b-44ec-8910-904f1c0f24c2",
            "sourceColumn": "assists",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "goals",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "459cd52a-5c08-46b7-9fd0-dce5f55e0ab6",
            "sourceColumn": "goals",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "ownGoals",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "25040423-f68a-403b-b26d-371964bd94bb",
            "sourceColumn": "ownGoals",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "redCards",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "75995415-f7a1-42f0-9ce1-d46f60ee3f41",
            "sourceColumn": "redCards",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "shirtNumber",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "afc77284-dd7e-4d19-8be7-aa9def23297e",
            "sourceColumn": "shirtNumber",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "yellowCards",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ed84bc3b-6dd4-46f4-86ea-0395c947f1e6",
            "sourceColumn": "yellowCards",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "minute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c7fae0f6-327e-471b-9266-e68700d8d1e4",
            "sourceColumn": "minute",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8556e2ab-2541-4076-9cb3-73ee634bdd86",
            "sourceColumn": "type",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f784e976-6934-41e8-99c4-68fc7599c34c",
        "partitions": [
          {
            "name": "scouting match_formation",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"prov-sql-azure.database.windows.net\", \"micro-scout\"),",
                "    scouting_match_formation = Origem{[Schema=\"scouting\",Item=\"match_formation\"]}[Data]",
                "in",
                "    scouting_match_formation"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "scouting match_lineup",
        "columns": [
          {
            "name": "match",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "a1cf6318-7520-4d17-bbb0-c242faf323e7",
            "sourceColumn": "match",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "e6618ae3-fee1-437f-a294-9bbda0709e6f",
            "sourceColumn": "team",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "period",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "168ca50b-b165-4fe4-b2e6-eada99a655a8",
            "sourceColumn": "period",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "second",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "68d02c28-a036-48ac-8423-babe5c316874",
            "sourceColumn": "second",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "match_lineup_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "3a394f2f-b2b9-454d-83db-456a6bd61403",
            "sourceColumn": "match_lineup_id",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "lineup",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f6a98ec2-c65a-4656-a9b8-1d555b69a346",
            "sourceColumn": "lineup",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "79bd99de-d8ef-4b2e-8ac3-2d5a9e41388a",
        "partitions": [
          {
            "name": "scouting match_lineup",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"prov-sql-azure.database.windows.net\", \"micro-scout\"),",
                "    scouting_match_lineup = Origem{[Schema=\"scouting\",Item=\"match_lineup\"]}[Data]",
                "in",
                "    scouting_match_lineup"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "scouting match_lineup_player_position",
        "columns": [
          {
            "name": "match_lineup_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "e8844bd3-cd58-49b0-a9ca-b5d4ae3bbcdf",
            "sourceColumn": "match_lineup_id",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "player",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "4679ca6b-612b-47d2-bf9e-76576b8f7260",
            "sourceColumn": "player",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "position",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "e197fed1-1719-4247-bd9f-a06a4cb2bc8a",
            "sourceColumn": "position",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cda535af-b2c2-4b5e-85ac-d35bd2871009",
        "partitions": [
          {
            "name": "scouting match_lineup_player_position",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"prov-sql-azure.database.windows.net\", \"micro-scout\"),",
                "    scouting_match_lineup_player_position = Origem{[Schema=\"scouting\",Item=\"match_lineup_player_position\"]}[Data]",
                "in",
                "    scouting_match_lineup_player_position"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "scouting match_substitution",
        "columns": [
          {
            "name": "match",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "44058396-f3fc-4525-9f08-2ae049a1f366",
            "sourceColumn": "match",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "playerIn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "396d4d64-ffa4-4dc3-a9c1-f00fd7f604ed",
            "sourceColumn": "playerIn",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "playerOut",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "a38e2d17-ac8a-4014-b377-7402134fafe1",
            "sourceColumn": "playerOut",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ec8b8145-48c1-404d-8dc9-2d6ebe52272a",
            "sourceColumn": "team",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "minute",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1a2702c9-5627-4cb3-819b-c9e1e0c00fcb",
            "sourceColumn": "minute",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "bc595e4a-7265-4b24-b71c-c5bf9128050a",
        "partitions": [
          {
            "name": "scouting match_substitution",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"prov-sql-azure.database.windows.net\", \"micro-scout\"),",
                "    scouting_match_substitution = Origem{[Schema=\"scouting\",Item=\"match_substitution\"]}[Data]",
                "in",
                "    scouting_match_substitution"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "scouting player",
        "columns": [
          {
            "name": "idplayer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "794dc2b9-a189-443e-ab08-c62c51e200ee",
            "sourceColumn": "idplayer",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f84b1b0e-ab03-43cb-b450-c27e4ca1fbf3",
            "sourceColumn": "name",
            "sourceProviderType": "nvarchar(100)",
            "summarizeBy": "none"
          },
          {
            "name": "short_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "69ab1fb3-7596-45de-9c20-328ed745d8b4",
            "sourceColumn": "short_name",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "birth_area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "68299061-de76-40a1-8603-e4782ef19315",
            "sourceColumn": "birth_area",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "birth_date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ac97dee3-08a9-4b3a-a459-c0969ce0f7d9",
            "sourceColumn": "birth_date",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "image",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "ImageUrl",
            "dataType": "string",
            "lineageTag": "1c2bf659-84c4-4d2b-b668-0a4f46cb1eb5",
            "sourceColumn": "image",
            "sourceProviderType": "nvarchar(200)",
            "summarizeBy": "none"
          },
          {
            "name": "foot",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dde0d7e0-8e4e-4317-8edb-ec87e955b7c9",
            "sourceColumn": "foot",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "height",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "53f8670d-64f0-423d-93e3-fb98cd74e424",
            "sourceColumn": "height",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "weight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5c710bb6-2ac4-49eb-bbe2-52429c9634d8",
            "sourceColumn": "weight",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89fb0433-6048-4f18-a3db-da6df19991db",
            "sourceColumn": "status",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cc99c5a4-e1e4-4cc0-99b8-1bea0497ee7a",
            "sourceColumn": "gender",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "role_code2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "edb4c33f-4d03-45ec-81dc-0d7666e02d0a",
            "sourceColumn": "role_code2",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "role_code3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2dcd471-11cb-44c1-9cd0-d2a9326fed17",
            "sourceColumn": "role_code3",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "role_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d11d92a-d0c5-4438-865d-d1db8267795c",
            "sourceColumn": "role_name",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "market_value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0a94bc8a-d273-465c-ac07-68ae48bfefd6",
            "sourceColumn": "market_value",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "contract_expiration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "017db15d-3f6b-4058-9071-c443f95e5b70",
            "sourceColumn": "contract_expiration",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "contract_agency",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "52d15c7b-7251-4f1d-b723-a48fa284fd0f",
            "sourceColumn": "contract_agency",
            "sourceProviderType": "nvarchar(200)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "eaf61fc1-d37b-49f2-bd98-06152729c275",
        "partitions": [
          {
            "name": "scouting player",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"prov-sql-azure.database.windows.net\", \"micro-scout\"),",
                "    scouting_player = Origem{[Schema=\"scouting\",Item=\"player\"]}[Data]",
                "in",
                "    scouting_player"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "scouting player_match_stats",
        "columns": [
          {
            "name": "idplayer_match_stats",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "bf868fbf-861a-4d31-9cca-08b02d6a916e",
            "sourceColumn": "idplayer_match_stats",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "match",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f6332304-5146-4488-9b5f-05294cd557d9",
            "sourceColumn": "match",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "player",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ce9a05c6-eb58-4745-ad36-e2c02b43791f",
            "sourceColumn": "player",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "offensiveDuels",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "85c85b50-ba8b-4bc6-a157-08d7d3d93343",
            "sourceColumn": "offensiveDuels",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "progressivePasses",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2ec9cc4d-3041-4e04-be7d-0270d9c7cfcc",
            "sourceColumn": "progressivePasses",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "forwardPasses",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2d9152c5-dbdd-4a25-9128-777276b78eb5",
            "sourceColumn": "forwardPasses",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "crosses",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "bda99993-806a-4356-9067-bc3f0100535c",
            "sourceColumn": "crosses",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "keyPasses",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c38462ed-f775-4e9d-b522-5d1ff6a38399",
            "sourceColumn": "keyPasses",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "defensiveDuels",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b08b46c1-0948-4604-b9b6-532b39ea5ce2",
            "sourceColumn": "defensiveDuels",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "interceptions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ee947f37-b188-48a0-a274-a03496c7961b",
            "sourceColumn": "interceptions",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "recoveries",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fbdebbcd-1640-44cc-8b4b-531b6bfae664",
            "sourceColumn": "recoveries",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "successfulPasses",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7b234a87-2ca6-4de7-a611-b4910843a182",
            "sourceColumn": "successfulPasses",
            "sourceProviderType": "real",
            "summarizeBy": "sum"
          },
          {
            "name": "longPasses",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "be5133f6-91bd-43be-866c-293383f9abc7",
            "sourceColumn": "longPasses",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "aerialDuels",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "86d01110-794c-447b-96b0-b320c9e3b6cd",
            "sourceColumn": "aerialDuels",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "losses",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "764decf0-b88c-46f0-a8a9-1b5982a22b1e",
            "sourceColumn": "losses",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "ownHalfLosses",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8b9543e9-bcd4-4829-be0b-1b1ab6058262",
            "sourceColumn": "ownHalfLosses",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "opponentHalfRecoveries",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9a99bd73-9cd3-4f2d-b401-57e9f7cc9981",
            "sourceColumn": "opponentHalfRecoveries",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "goalKicks",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b4ebadd0-31b2-46fa-902d-dc3cb158a14c",
            "sourceColumn": "goalKicks",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "receivedPass",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c2dbcb06-011e-46d7-8538-d8c084f2011c",
            "sourceColumn": "receivedPass",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "dribbles",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "64e66611-ebec-468a-b29b-5feb42d8edb2",
            "sourceColumn": "dribbles",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "touchInBox",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3ee07d5e-ba3e-49e1-9cd0-6a8e884d63f2",
            "sourceColumn": "touchInBox",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "0160f295-6297-4fab-afe6-3cda9769fbbc",
        "partitions": [
          {
            "name": "scouting player_match_stats",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"prov-sql-azure.database.windows.net\", \"micro-scout\"),",
                "    scouting_player_match_stats = Origem{[Schema=\"scouting\",Item=\"player_match_stats\"]}[Data]",
                "in",
                "    scouting_player_match_stats"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "scouting player_positions",
        "columns": [
          {
            "name": "player",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "e4dc75ce-b600-4aa9-ae4c-d0bdc07f09e5",
            "sourceColumn": "player",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "percent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "620c1e13-549c-4e3c-af15-3f5ded329bd9",
            "sourceColumn": "percent",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isNullable": false,
            "lineageTag": "36ba1329-d1b6-472c-9345-645546be6130",
            "sourceColumn": "code",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc32361d-becf-4d72-9d8b-9416d7c6e38d",
            "sourceColumn": "name",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "team_competition_season",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "8486ac25-82e2-448d-bc33-9e79a19269e9",
            "sourceColumn": "team_competition_season",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "23c5736f-2c86-412e-b061-c24b5d917f84",
        "partitions": [
          {
            "name": "scouting player_positions",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"prov-sql-azure.database.windows.net\", \"micro-scout\"),",
                "    scouting_player_positions = Origem{[Schema=\"scouting\",Item=\"player_positions\"]}[Data]",
                "in",
                "    scouting_player_positions"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "scouting round",
        "columns": [
          {
            "name": "competition_season",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "b9497a2d-b6d5-4f10-ae68-4ac76d1441b4",
            "sourceColumn": "competition_season",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "startDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isNullable": false,
            "lineageTag": "9b98c8c1-9dbe-4e2e-ba21-411fa01d486d",
            "sourceColumn": "startDate",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "endDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isNullable": false,
            "lineageTag": "141dc61e-bbd9-486b-b2be-00a396054d67",
            "sourceColumn": "endDate",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "26af5163-ee5b-4137-968a-1417d59b8392",
            "sourceColumn": "name",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3057c998-7388-4b41-8484-c2340a366832",
        "partitions": [
          {
            "name": "scouting round",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"prov-sql-azure.database.windows.net\", \"micro-scout\"),",
                "    scouting_round = Origem{[Schema=\"scouting\",Item=\"round\"]}[Data]",
                "in",
                "    scouting_round"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "scouting team",
        "columns": [
          {
            "name": "idteam",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "58d71fd6-639f-4241-9b69-89248f8b5705",
            "sourceColumn": "idteam",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e898c887-c35e-4290-a987-79366197c3c6",
            "sourceColumn": "name",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "official_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "011bf4de-3193-4b72-a0bd-c6013ece4a19",
            "sourceColumn": "official_name",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "icon",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7431b9da-964d-4b11-aab3-f3f847f6f8bf",
            "sourceColumn": "icon",
            "sourceProviderType": "nvarchar(200)",
            "summarizeBy": "none"
          },
          {
            "name": "gender",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af5be818-e761-408e-b5ee-0eceb3eceaa2",
            "sourceColumn": "gender",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9cc54340-e31e-4282-99a1-c43addfd7249",
            "sourceColumn": "type",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "city",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6054767e-7417-4d28-b717-254fefecadf2",
            "sourceColumn": "city",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ed6eb5f-eca4-43a1-aeb4-70a952582609",
            "sourceColumn": "category",
            "sourceProviderType": "nvarchar(45)",
            "summarizeBy": "none"
          },
          {
            "name": "area",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f0e390d4-f0ee-43aa-897d-cfee5407768b",
            "sourceColumn": "area",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "33412412-83e4-4093-a956-5579f45db61b",
        "partitions": [
          {
            "name": "scouting team",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"prov-sql-azure.database.windows.net\", \"micro-scout\"),",
                "    scouting_team = Origem{[Schema=\"scouting\",Item=\"team\"]}[Data]",
                "in",
                "    scouting_team"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "scouting team_competition_season",
        "columns": [
          {
            "name": "idteam_competition_season",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "299eccce-d49a-4516-9961-a4951b47331d",
            "sourceColumn": "idteam_competition_season",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "competition_season",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "50048fb5-a87c-4534-a184-33b959659412",
            "sourceColumn": "competition_season",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "team",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isNullable": false,
            "lineageTag": "9d282e59-0a6f-423b-9c6c-ef182c071c30",
            "sourceColumn": "team",
            "sourceProviderType": "int",
            "summarizeBy": "none"
          },
          {
            "name": "totalDraws",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a5161404-b89f-4038-be97-66332386b219",
            "sourceColumn": "totalDraws",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "totalGoalsAgainst",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4a6e5ed7-9795-400e-82c6-c4cc2e5995a5",
            "sourceColumn": "totalGoalsAgainst",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "totalGoalsFor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6eae7c23-2cf6-4736-8101-46a75e20790d",
            "sourceColumn": "totalGoalsFor",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "totalLosses",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0b7beda9-4b8f-4fd4-bfff-171544d7f3f5",
            "sourceColumn": "totalLosses",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "totalPlayed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b134ae9d-6482-4d50-b239-6fc4de59b7ee",
            "sourceColumn": "totalPlayed",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "totalPoints",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "59263bfe-ae0b-4733-9933-9c8e02096c80",
            "sourceColumn": "totalPoints",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "totalWins",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "23298009-fea7-4574-bc70-760e6a6bcf84",
            "sourceColumn": "totalWins",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "27a5097d-7e9b-4faf-ad35-283adb7b5d03",
        "partitions": [
          {
            "name": "scouting team_competition_season",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Origem = Sql.Database(\"prov-sql-azure.database.windows.net\", \"micro-scout\"),",
                "    scouting_team_competition_season = Origem{[Schema=\"scouting\",Item=\"team_competition_season\"]}[Data]",
                "in",
                "    scouting_team_competition_season"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}