name: Deploy ETL to VM

on:
  workflow_dispatch: # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get ssh key 
      run: |
        echo "{{ secrets.SSH_PRIVATE_KEY }}"  > ~/.ssh/id_rsa
        
    - name: Delete Remote ETL Folder
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'rm -rf /home/${{ secrets.SSH_USER }}/etl'

    - name: Copy ETL Folder to Remote VM
      run: |
        scp -i ~/.ssh/id_rsa -r ./etl ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}
