name: Deploy ETL to VM

on:
  workflow_dispatch: # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Create ~/.ssh directory
      run: mkdir -p /.ssh

    - name: Add remote host to known_hosts
      run: |
        ssh-keyscan -H -p 22 ${{ secrets.SSH_HOST }} >> /.ssh/known_hosts

    - name: Get ssh key 
      run: |
        echo "{{ secrets.SSH_PRIVATE_KEY }}"  > key
        
    - name: Delete Remote ETL Folder
      run: |
        ssh -i key ${{ secrets.SSH_USER }}@13.94.209.172 'rm -rf /home/${{ secrets.SSH_USER }}/etl'

    - name: Copy ETL Folder to Remote VM
      run: |
        scp -i key -r ./etl ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}
